### ISSUE TITLE
Date Picker on APEX 21.1.0 

### ISSUE THREAD

**Issue by apushenko** [phartenfeller/apex-slide-over-plugin#2]
Thank you for your fantastic plugin that helps improve UX with just a few changes! :)
We just migrated on the latest APEX 21.1.0 and found that when we place in SlideOver region DatePicker item, the region doesn't open at all. Could you please take a look at it?

**Comment by phartenfeller** [comment]
Hi, thanks!

This is a strange bug 😄. I was able to reproduce it and am searching for a fix.

**Comment by phartenfeller** [comment]
Seems like I could fix it. Can you test it by downloading this updated Plug-In file and import it into your app?

https://github.com/phartenfeller/apex-slide-over-plugin/releases/download/v1.2-beta/region_type_plugin_dev_hartenfeller_slideover.sql

**Comment by apushenko** [comment]
Philipp, thank you very much for your super quick response and fix. The issue has been fixed.
